import os
import json
from pathlib import Path

def create_project(project_type: str, name: str) -> str:
    if not name:
        name = "new-project"
    
    # Clean the name
    name = name.replace(" ", "-").lower()
    project_path = Path(name)
    
    if project_path.exists():
        raise Exception(f"Directory '{name}' already exists.")
        
    project_path.mkdir()
    
    # Add GitHub Actions YAML for all projects
    github_dir = project_path / ".github" / "workflows"
    github_dir.mkdir(parents=True, exist_ok=True)
    with open(github_dir / "main.yml", "w") as f:
        f.write("name: RepoForge CI\non: [push]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n      - name: Build\n        run: echo Building " + name + "...")
    
    if project_type == "node" or project_type == "expressjs":
        # Create standard express/node project
        package_json = {
            "name": name,
            "version": "1.0.0",
            "description": f"{project_type} project initialized by RepoForge",
            "main": "index.js",
            "scripts": {
                "start": "node index.js",
                "dev": "nodemon index.js"
            },
            "dependencies": {
                "express": "^4.18.2",
                "cors": "^2.8.5",
                "dotenv": "^16.3.1"
            } if project_type == "expressjs" else {}
        }
        
        with open(os.path.join(name, "package.json"), "w") as f:
            json.dump(package_json, f, indent=2)
            
        index_content = ""
        if project_type == "expressjs":
            index_content = """const express = require('express');
const cors = require('cors');
require('dotenv').config();

const app = express();
app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 3000;

app.get('/', (req, res) => {
  res.json({ message: 'Welcome to your new Express API!' });
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
"""
        else:
            index_content = """console.log('Hello from your new Node project!');"""
            
        with open(os.path.join(name, "index.js"), "w") as f:
            f.write(index_content)
            
        with open(os.path.join(name, ".env"), "w") as f:
            f.write("PORT=3000\n")
            
        with open(os.path.join(name, ".gitignore"), "w") as f:
            f.write("node_modules/\n.env\n")
            
        with open(os.path.join(name, "README.md"), "w") as f:
            f.write(f"# {name}\\n\\nGenerated by RepoForge CLI.\\n\\n## Setup\\n`npm install`\\n`npm start`")
            
        return f"Created {project_type} project in '{name}'. Run 'cd {name}' and 'npm install'."
        
    elif project_type == "react":
        # Simulate react scaffolding (in real life we'd use npx create-react-app or vite)
        # We can just return a helpful message to the user that we are using Vite.
        # But since the user wants it to directly create folder and files, we'll make a basic template.
        package_json = {
            "name": name,
            "version": "1.0.0",
            "scripts": {
                "dev": "vite",
                "build": "vite build",
                "preview": "vite preview"
            },
            "dependencies": {
                "react": "^18.2.0",
                "react-dom": "^18.2.0"
            },
            "devDependencies": {
                "@vitejs/plugin-react": "^4.2.1",
                "vite": "^5.0.0"
            }
        }
        with open(os.path.join(name, "package.json"), "w") as f:
            json.dump(package_json, f, indent=2)
            
        os.makedirs(os.path.join(name, "src"))
        with open(os.path.join(name, "index.html"), "w") as f:
            f.write("<!DOCTYPE html>\\n<html lang='en'>\\n<body>\\n<div id='root'></div>\\n<script type='module' src='/src/main.jsx'></script>\\n</body>\\n</html>")
            
        with open(os.path.join(name, "src", "main.jsx"), "w") as f:
            f.write("import React from 'react';\\nimport ReactDOM from 'react-dom/client';\\nimport App from './App.jsx';\\n\\nReactDOM.createRoot(document.getElementById('root')).render(<App />);")
            
        with open(os.path.join(name, "src", "App.jsx"), "w") as f:
            f.write("export default function App() {\\n  return <h1>Hello React!</h1>;\\n}")
            
        return f"Created React project in '{name}'. Run 'cd {name}' and 'npm install'."
        
    else:
        # Generic fallback
        os.makedirs(os.path.join(name, "src"), exist_ok=True)
        with open(os.path.join(name, "README.md"), "w") as f:
            f.write(f"# {name}\\n\\nGenerated by RepoForge CLI.")
        return f"Created generic project folder '{name}'."
